### ISSUE TITLE
Issue building solution

### ISSUE THREAD

**Issue by teh-masterer** [lextudio/sharpsnmplib-samples#13]
Always had issues building this solution, used to be resolved by adding Build Target for Build and Clean in the Samples.Engine.csproj. 
It no longer compiles, complaining about not finding CollectUpToDateCheckBuiltDesignTime" in the project. If I manually add it to the build, it will go on about something else.
It'll then give me this:
NETSDK1004	Assets file 'C:\Users\admin\source\repos\sharpsnmplib-samples\Samples.Engine\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	Samples.Engine	
This seems to be a byproduct of _dotnet restore_ not being able to run because of the aforementioned. 

This applies for Visual Studio 16.8.3 directly after cloning the project.

**Comment by lextm** [comment]
As developers we can only guarantee the projects work on clean environments, such as Azure Pipelines hosted machines,

https://dev.azure.com/lextudio/sharpsnmp/_build?definitionId=10&_a=summary

You might refer to our environment specifications for more details,

https://github.com/lextudio/sharpsnmplib-samples/blob/master/azure-pipelines.yml

We won't be able to help on individual cases like yours, as your machine setup can be quite complicated due to various other stuffs you installed/configured.

**Comment by teh-masterer** [comment]
Thank you for your response, @lextm.
I completely understand. Since I'm using these examples for learning and not production, I have them running on a Windows 10 VM and not a Docker. For now I've had to make a new project with adaptions of the relevant files, and that works fine.. I didn't find an easy solution to compiling the solution as-is at least.

**Comment by rmbl-xD** [comment]
I have the same problem. New Machine and installed only Visual studio with all features selected.
